In [1]:
import numpy as np
import pandas as pd


In [243]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt', header=None)

In [244]:
data.head()

(1372, 5)

In [245]:
finit=data.iloc[0,0:4]
tinit=data.iloc[-2,0:4]

In [246]:
finit,tinit

(0    3.62160
 1    8.66610
 2   -2.80730
 3   -0.44699
 Name: 0, dtype: float64, 0    -3.5637
 1    -8.3827
 2    12.3930
 3    -1.2823
 Name: 1370, dtype: float64)

In [247]:
finit=(np.array(finit))
tinit=(np.array(tinit))

In [248]:
finit=finit.reshape(1,4)
tinit=tinit.reshape(1,4)

In [249]:
data=data.sample(frac=1).reset_index(drop=True)

In [250]:
Xtr=data.iloc[0:1172,[0,1,2,3]]
Xcv=data.iloc[1172:1272,[0,1,2,3]]
Xte=data.iloc[1272:1372,[0,1,2,3]]
Ytr=data.iloc[0:1172,4]
Ycv=data.iloc[1172:1272,4]
Yte=data.iloc[1272:1372,4]

In [251]:
data.head()

0         1        2        3  4
0 -0.38388  -1.04710  8.05140  0.49567  0
1 -0.17296  -1.18160  1.38180  0.73360  1
2 -1.38850  12.50260  0.69118 -7.54870  0
3 -2.31420   2.08380 -0.46813 -1.67670  1
4  5.27560   0.13863  0.12138  1.14350  0

In [252]:
Xtr=np.array(Xtr)
Ytr=np.array(Ytr)


In [253]:
U=np.ones(Ytr.shape)

In [254]:
cost0=((Xtr-finit)**2).sum(axis=1)
cost1=((Xtr-tinit)**2).sum(axis=1)

In [255]:
cost0, cost1

(array([229.19009784, 130.31823244, 102.49348149, ...,  17.99852268,
         17.62157369,   2.80229989]),
 array([ 85.93295047, 188.66333721, 617.1276114 , ..., 659.48737098,
        671.22010986, 554.9192815 ]))

In [256]:
U= cost0 > cost1
U=U.reshape(1172,1)

In [257]:
U

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [258]:
tinit=((Xtr*U).sum(axis=0))/(U.sum())
finit=((Xtr*(np.invert(U))).sum(axis=0))/((np.invert(U)).sum())

In [259]:
finit, tinit

(array([ 0.78008343,  4.6713848 , -0.64520102, -1.58467466]),
 array([-0.74219512, -5.67379491,  7.15028333, -0.19344168]))

In [260]:
for _ in range(150000):
    cost0=((Xtr-finit)**2).sum(axis=1)
    cost1=((Xtr-tinit)**2).sum(axis=1)
    U= cost0 > cost1
    U=U.reshape(1172,1)
    tinit=((Xtr*U).sum(axis=0))/(U.sum())
    finit=((Xtr*(np.invert(U))).sum(axis=0))/((np.invert(U)).sum())

In [261]:
tinit

array([-0.43527164, -4.78624829,  6.22217727, -0.04589726])

In [238]:
Xtr

array([[-0.2951 ,  9.0489 , -0.52725, -2.0789 ],
       [-1.4781 ,  0.14277, -1.1622 , -0.48579],
       [-1.6641 , -1.3678 ,  1.997  ,  0.52283],
       ...,
       [ 0.29961,  7.1328 , -0.31475, -1.1828 ],
       [ 4.2134 , -2.806  ,  2.0116 ,  0.67412],
       [-1.8343 , -6.5907 ,  5.6429 ,  0.54998]])

In [262]:
U

array([[ True],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [263]:
(Ytr.reshape(1172,1) ==U).mean()

0.6032423208191127

In [264]:
Xte=np.array(Xte)
Yte=np.array(Yte)
Xcv=np.array(Xcv)
Ycv=np.array(Ycv)

In [266]:
costCV0=((Xcv-finit)**2).sum(axis=1)
costCV1=((Xcv-tinit)**2).sum(axis=1)
costTE0=((Xte-finit)**2).sum(axis=1)
costTE1=((Xte-tinit)**2).sum(axis=1)

In [267]:
UCV= costCV0 > costCV1
UTE= costTE0 > costTE1

In [269]:
(UCV == Ycv).mean()

0.64

In [270]:
(UTE == Yte).mean()

0.63